#!/usr/bin/env bash
# Apeiron docker deployment (matches the /opt/monoize runbook conventions on
# 64.90.22.212). Run ON the production host from a repo checkout:
#   ./apeiron/deploy.sh [rev]
#
# Steps: build web dist + release server inside the monoize-builder image,
# cross-build the static Go worker, assemble runtime images apeiron-server:<rev>
# / apeiron-worker:<rev>, bootstrap /opt/apeiron/env.sh once (generated
# secrets), then (re)start both containers on the host network. The platform
# container must additionally export the MONOIZE_* values printed at the end.
set -euo pipefail

REV=${1:-$(git rev-parse --short HEAD 2>/dev/null || echo dev)}
SRC=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
APEIRON_SRC=$SRC/apeiron
TARGET=/opt/apeiron
BUILDER=${APEIRON_BUILDER_IMAGE:-monoize-builder:30dca059}

echo "==> building apeiron web + server (rev $REV, builder $BUILDER)"
docker run --rm -v "$APEIRON_SRC":/src -w /src "$BUILDER" bash -lc '
  set -euo pipefail
  source /root/.cargo/env
  cd /src/web && bun install --frozen-lockfile && bun run build
  cd /src/server && cargo build --locked --release
'
SERVER_BIN=$APEIRON_SRC/server/target/release/apeiron-server
test -x "$SERVER_BIN"

echo "==> building apeiron worker (static go binary)"
docker run --rm -v "$APEIRON_SRC":/src -w /src/worker golang:1.23-bookworm \
  env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o /src/worker-bin/apeiron-worker .
mkdir -p "$APEIRON_SRC/worker-bin"
# the container wrote through the mount; ensure it landed
test -x "$APEIRON_SRC/worker-bin/apeiron-worker" || {
  docker run --rm -v "$APEIRON_SRC":/src golang:1.23-bookworm \
    cat /src/worker-bin/apeiron-worker > "$APEIRON_SRC/worker-bin/apeiron-worker"
  chmod +x "$APEIRON_SRC/worker-bin/apeiron-worker"
}

echo "==> runtime images"
mkdir -p "$TARGET"
cat > "$TARGET/Dockerfile.server" <<'EOF'
FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY apeiron-server /usr/local/bin/apeiron-server
USER 1000:1000
ENTRYPOINT ["apeiron-server"]
EOF
cp "$SERVER_BIN" "$TARGET/apeiron-server"
docker build -q -t "apeiron-server:$REV" -f "$TARGET/Dockerfile.server" "$TARGET"

cat > "$TARGET/Dockerfile.worker" <<'EOF'
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY apeiron-worker /usr/local/bin/apeiron-worker
USER 1000:1000
ENTRYPOINT ["apeiron-worker"]
EOF
cp "$APEIRON_SRC/worker-bin/apeiron-worker" "$TARGET/apeiron-worker"
docker build -q -t "apeiron-worker:$REV" -f "$TARGET/Dockerfile.worker" "$TARGET"

mkdir -p "$TARGET/data"
chown -R 1000:1000 "$TARGET/data"

# One-time env bootstrap; existing values are never overwritten.
if [ ! -f "$TARGET/env.sh" ]; then
  BRIDGE_TOKEN=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  WORKER_TOKEN=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  BRIDGE_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  cat > "$TARGET/env.sh" <<EOF
# Generated by apeiron/deploy.sh. Edit and re-run to apply.
APEIRON_LISTEN=127.0.0.1:8090
APEIRON_DATABASE_DSN=sqlite://./data/apeiron.db
APEIRON_ASSETS_DIR=./data/assets
APEIRON_PLATFORM_URL=https://www.lynshen.org
APEIRON_BRIDGE_URL=http://127.0.0.1:8080
APEIRON_BRIDGE_SERVICE_TOKEN=$BRIDGE_TOKEN
APEIRON_WORKER_TOKEN=$WORKER_TOKEN
MONOIZE_STUDIO_BRIDGE_SECRET=$BRIDGE_SECRET
MONOIZE_STUDIO_BRIDGE_SERVICE_TOKEN=$BRIDGE_TOKEN
MONOIZE_APEIRON_URL=https://apeiron.lynshen.org
EOF
  chmod 600 "$TARGET/env.sh"
  echo "==> generated $TARGET/env.sh"
fi

set -a
. "$TARGET/env.sh"
set +a

echo "==> starting containers"
docker rm -f apeiron-server apeiron-worker 2>/dev/null || true
docker run -d --name apeiron-server --restart unless-stopped --network host \
  --user 1000:1000 -v "$TARGET/data":/app/data \
  -e APEIRON_LISTEN -e APEIRON_DATABASE_DSN -e APEIRON_ASSETS_DIR \
  -e APEIRON_PLATFORM_URL -e APEIRON_BRIDGE_URL \
  -e APEIRON_BRIDGE_SERVICE_TOKEN -e APEIRON_WORKER_TOKEN \
  "apeiron-server:$REV"
docker run -d --name apeiron-worker --restart unless-stopped --network host \
  --user 1000:1000 \
  -e APEIRON_SERVER_URL=http://127.0.0.1:8090 -e APEIRON_WORKER_TOKEN \
  -e WORKER_ID=worker-lynshen-1 \
  "apeiron-worker:$REV"

echo
echo "Apeiron deployed (rev $REV). Platform container additionally needs:"
grep -E "^MONOIZE_" "$TARGET/env.sh"
echo "Then restart the monoize container with those -e values."
echo "Caddy: point apeiron.<domain> at 127.0.0.1:8090 and reload."
